spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodcataloguedb
    password: password
    username: root
restaurantribbon:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8300,lhttp://localhost:8301
