spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    password: password
    username: root
eureka:
  client:
     service-url:
       defaultZone: http://localhost:8761/eureka/      
